version: "3.8"

services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports:
      - "1883:1883"

  publisher:
    build: .
    command: python src/mqtt/publisher.py
    depends_on:
      - mosquitto
    environment:
      MQTT_BROKER: mosquitto
      MQTT_PORT: 1883
      TRUCK_ID: TRUCK_001
      MQTT_SENSOR_TOPIC: logibridge/trucks/TRUCK_001/sensors

  logiedge:
    build: .
    command: python src/mqtt/subscriber.py
    depends_on:
      - mosquitto
    environment:
      MQTT_BROKER: mosquitto
      MQTT_PORT: 1883
      TRUCK_ID: TRUCK_001
      MQTT_SENSOR_TOPIC: logibridge/trucks/TRUCK_001/sensors
      MQTT_INFERENCE_TOPIC: logibridge/trucks/TRUCK_001/inference
      MODEL_PATH: /app/data/tflite/model_fp32.tflite
    volumes:
      - ./logs:/app/logs
